pipeline {
    agent any
    
    environment {
        JAVA_HOME = '/usr/lib/jvm/java-21-amazon-corretto'
        PATH = "/opt/maven/bin:$JAVA_HOME/bin:$PATH"
        
        // Nexus Configuration - Update with your EC2 IP
        NEXUS_URL = "localhost:8081"
        NEXUS_CREDENTIAL_ID = "nexus-credentials"
    }
    
    options {
        skipStagesAfterUnstable()
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/skillupwithsachin/simple-java-maven-app.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
    stage('Upload to Nexus') {
            steps {
                withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIAL_ID, usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                    sh '''
                        mvn deploy -DskipTests \
                        -DaltDeploymentRepository=nexus::default::http://localhost:8081/repository/maven-snapshots/ \
                        -Dusername=$NEXUS_USER \
                        -Dpassword=$NEXUS_PASS
                    '''
                }
            }
        }
        
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}